fi = open("MINMAX.INP","r")
fo = open("MINMAX.OUT","w")
n = int(fi.readline())
ln = fi.readline()
a = ln.split(" ")
nhonhat=min(a)
lonnhat=max(a)
fo.write(str(nhonhat)+"\n")
fo.write(str(lonnhat))
fi.close()
fo.close()
